### ISSUE TITLE
How to handle models that do not expose all fields?

### ISSUE THREAD

**Issue by PaulWay** [Yupeek/django-rest-models#32]
An interface I'm talking to has a model with a `created_on` DateTimeField with `auto_now=True` set.  They don't expose this in the serializer class.  If I simply copy the model across, django-rest-models looks for the `created_on` field in the serializer output and doesn't find it.  Is there a way to tell django-rest-models which fields should be expected?  Or do I need to remove the hidden fields from my local version?

**Comment by ornoone** [comment]
your model in the «client» side should match exactly the serializer of your API.

if you don't expose your `created_on` field, this mean you don't need it in the client side. if you don't need it in your client side, you should remove this field from the model, since it won't be used.

at Yupeek, we use this lib to simplify front-end models which contain only used fields, even if your api store many more fields.
